return {}
--     {
--         "mfussenegger/nvim-jdtls",
--         ft = { "java" },
--         dependencies = {
--             "mfussenegger/nvim-dap",
--         },
--     },
--     vim.keymap.set("n", "<F5>", function()
--         require("jdtls.dap").setup_dap_main_class_configs({
--             on_ready = function()
--                 require("dap").continue()
--             end,
--         })
--     end)
