;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(file-name-history evil-ex-history project--dir-history consult--buffer-history))
(setq file-name-history '("~/dotfiles/"))
(setq evil-ex-history '("w" "wq" "w" "q"))
(setq consult--buffer-history '("~􀀀"))
(setq corfu-history 'nil)
